### ISSUE TITLE
Handle CellVolume

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/tsfc#1]
On non-affine cells, we should compute `CellVolume` by integrating `detJ` over the reference cell (presumably using the same quadrature scheme as the rest of the form).  To do this, we need to emit a separate quadrature loop for the cell volume that occurs before the main quad-loop that uses it.

**Comment by miklos1** [comment]
We just need to get a translated `|J|` somehow when we translate `CellVolume`, then it's just:

    IndexSum(|J|, quadrature_index)

if `|J|` depends on quadrature_index, otherwise:

    |J|

**Comment by tkarna** [comment]
Any progress on this? Is FacetArea going to be supported as well? Many stabilization methods use the ratio CellVolume/FacetArea as a mesh length scale estimate.

**Comment by miklos1** [comment]
It's good that you mention facets, because I was wondering whether to integrate `|J|` on the same quadrature points as the rest of the form, or just using the "correct" degree. However, when one uses `CellVolume` in a facet integral, then it cannot be sufficient to use the same quadrature points that we use to integrate on the facet. On a similar note, I believe `FacetArea` only makes sense in a facet integral, doesn't it?

**Comment by tkarna** [comment]
> On a similar note, I believe FacetArea only makes sense in a facet integral, doesn't it?

I think so.

**Comment by miklos1** [comment]
I'll look at this tomorrow.

**Comment by miklos1** [comment]
I believe all we need to do is to compile the integration of 1 in the physical space down to GEM, and then during the UFL -> GEM translation phase of the actual form we just insert the previously generated GEM every time we encounter a `CellVolume` or `FacetArea` node.

I have to refactor the driver before this could actually be as easy as it sounds.

**Comment by wence-** [comment]
Careful to make sure you integrate against the correct measure for `FacetArea`.

**Comment by miklos1** [comment]
Yes.
 * `CellVolume` -> always `dx`
 * `FacetArea` -> same measure as for the form, only allowed with facet integrals

**Comment by miklos1** [comment]
Branch `cellvolume` seems to support both `CellVolume` and `FacetArea`. I just need to clean up, test etc. and then it can go to master.

**Comment by miklos1** [comment]
Working on this seems to uncover quite a few different problems in our stack:
 * [Degree estimation doesn't cater for non-affine cell geometry](https://bitbucket.org/fenics-project/ufl/issues/80/degree-estimation-doesnt-cater-for-non)
 * Quadrature degree type depends on the integrand only (firedrakeproject/firedrake#744)
 * I don't even understand any more why did Martin's original (pull back first) degree estimation give high numbers on affine. I seem to get zero for Jacobian terms.
 * Restriction propagation in UFL is bogus. It assumes that a bunch of stuff are for integral scaling only, while they are also required for FacetArea / CellVolume.

I hope that's all.

**Comment by dorugeber** [comment]
@colinjcotter's opinion was always that we shouldn't care about the first of those.  Yes, this means that we return the wrong answer for `assemble(1.0*dx(quadratic_mesh))` when we could have done it correctly.  However, as soon as you do something not-quite-trivial (like, use a grad in your form), the resulting expression is no longer polynomial (due to inverse Jacobians), so exact quadrature goes out the window anyway.

You're then left between the defaults of "same as affine" or "estimate fully", and Colin leant on the former.  I think the justification is that "same as affine" is enough to get the order of convergence you expect in a problem.

Pullback-first degree estimation: I'd expect that to give high numbers on non-affine, but not on affine.  Perhaps grad(spatial_coordinate) was returning a degree > 0 previously?
