### ISSUE TITLE
Generated code for high-order bilinear forms causes stack overflow when run

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/tsfc#127]
The local matrix of a 15th-order bilinear form on a cube has 16^3 x 16^3 entries. With `double`s that is 128MB. The generation code may create several temporaries of that size, and all temporaries are allocated on the stack. This puts some stress on the stack.

On Linux, the following command seems to help in bash:

    ulimit -s unlimited

**Comment by wence-** [comment]
Arguably the correct answer is "don't do that!"

**Comment by wence-** [comment]
Although in general for complicated forms at high order there will be many temporaries: ISTR some of @FabioLuporini's optimisation work takes into account the working set size.  Can something similar be added here?  Or a rule in tsfc to heap-allocate "large" temporaries?

**Comment by miklos1** [comment]
A convergence of the `spectral` and `coffee` modes could reduce this by an order of magnitude or more I think.

**Comment by FabioLuporini** [comment]
If you're allocating that much memory, probably we could consider a different code generation strategy, because it might be better to recompute, rather than trading flops for memory. What temporaries are you allocating?

**Comment by miklos1** [comment]
@FabioLuporini: https://gist.github.com/miklos1/cfae2a01147f9d10487945757887abba

**Comment by FabioLuporini** [comment]
Probably some papers here hold useful suggestions: http://www.csc.lsu.edu/~gb/TCE/

How difficult is it to run a comparison between:
- the code in its current form allocating stuff on the heap
- the code w/o sum factorization 

Some random questions: what other frameworks such as DUNE or FEM++ do in similar scenarios? Do they do loop blocking? Do they mix it with sum factorization? Do they always employ the same approach ? Or am I too optimistic -- is this simply left to the users (good luck) ?

I think this could be further work for @tj-sun

**Comment by wence-** [comment]
Other frameworks get the user to write this code, so I don't know how to answer that question.

Even without sum factorisation, there is at least one 128MB temporary (the local tensor).  

For the laplacian on hexes at Q15 I don't see any 128MB temporaries other than the local tensor (`A[4096][4096]`), even in spectral mode.  But the flop counts are very different (obviously):

1. `flops(vanilla_) => 481640931993`
2. `flops(_coffee_)   => 287941055129`
3. `flops(spectral)  =>  __5153194649`

**Comment by dham** [comment]
Hi all,

I kind of suspect that the actual answer is that assembling matrices at degree 15 is so totally nuts that this is expected behaviour. Surely everyone who actually does that high order is doing matrix free.

Dr David Ham
Department of Mathematics
Imperial College London

On 18 Jul 2017, at 11:15, Lawrence Mitchell <notifications@github.com<mailto:notifications@github.com>> wrote:


Other frameworks get the user to write this code, so I don't know how to answer that question.

Even without sum factorisation, there is at least one 128MB temporary (the local tensor).

For the laplacian on hexes at Q15 I don't see any 128MB temporaries other than the local tensor (A[4096][4096]), even in spectral mode. But the flop counts are very different (obviously):

  1.  flops(vanilla_) => 481640931993
  2.  flops(_coffee_) => 287941055129
  3.  flops(spectral) => __5153194649

**Comment by rckirby** [comment]
Wouldn't the basis functions at quadrature points be the "wrong" 16^3 x 16^3 size as well as the resulting tensor, if one doesn't use the factored basis representation?  Gradients would be 3x larger.

But agreed that this is nuts in practice.  For the purposes of experiments, it might make sense to start from low order and ramp up until things break (or not for the factored representation/matrix free) rather than jumping to degree 15?

Is the story of what happened to Anders' computer during the process of putting H(div) and H(curl) elements into ffc well-known?  His student (and we know who she is) asked to run uniform p-refinement for Maxwell cavity eigenvalue problems on his workstation to get paper results.  We got a paper submitted and he got a random number generator in place of his floating point unit.  Moral: if you fully assemble 3d matrices with high order basis functions, you deserve whatever happens to you.

**Comment by wence-** [comment]
The factored representation is always used, this discussion is about the spectral optimisation mode blowing up the number of additional temporaries.

**Comment by sv2518** [comment]
I think "don't do that" is the right answer here.
