### ISSUE TITLE
Refactoriser breaks on complex nodes

### ISSUE THREAD

**Issue by IgorBaratta** [firedrakeproject/tsfc#166]
This happens when using TSFC as an FFC representation with complex scalars.
The error can be reproduced with the following code:

``` 
from ufl import *
from tsfc import ufl_utils
from tsfc.driver import compile_integral

element = FiniteElement("P", triangle, 1)
u, v = TrialFunction(element), TestFunction(element)
a = inner(u, v)*dx
parameters = {'scalar_type': 'double complex', 'mode': 'spectral'}

fd = ufl_utils.compute_form_data(a, complex_mode=True)
integral_data = fd.integral_data[0]
kernel = compile_integral(integral_data, fd, prefix=None, parameters=parameters)
```

**Comment by miklos1** [comment]
I believe the underlying issue is that the refactoriser cannot factorise through `conj`, `real`, and `imag` nodes.  UFLACS seems to have [a very short solution](https://github.com/FEniCS/ffcx/pull/67/files#diff-4af792e603004b1fe1552527dfeb2b8bR175). (Although it seems that they forgot to test for `real` and `imag` nodes, because I think they should exhibit the same issue.)

**Comment by wence-** [comment]
I think 79b10f5 fixes this by pushing `conj/real/imag` inside MonomialSum objects (broadly similar to the way conditional nodes are handled).
