### ISSUE TITLE
derivative of conditional

### ISSUE THREAD

**Issue by mmorandi** [firedrakeproject/tsfc#183]
[beam.zip](https://github.com/firedrakeproject/tsfc/files/2901410/beam.zip)
Consider the attached ufl, a test case distilled from a more complex code. All the source of `NaN`s are protected by conditionals.
The generated code (beam.h, attached, obtained with ffc -l dolfin -r tsfc) has these lines:

`double  t12  = ((((((t9) * (t9))) + (((t10) * (t10))))) + (((t11) * (t11))));`
`double  t14  = ((1) / (t12));`
`double  t15  = ((sin(t12)) * (t14));`
`double  t23  = (t13 ? 1 : 0);`
`double  t25  = (((t13 ? 0 : 1)) * (t14));`
`double  t27  = ((((t23) * (t24))) + (((t25) * (((((-1) * (((t15) * (t24))))) + (((t26) * (t24))))))));`

With null `t9`, `t10` and `t11` (i.e. `u_phi`) `t15` will be equal to `NaN`. In `t27` tsfc tried to reproduce the conditional by multiplying `t24` by `t23`, and summing the result to the product between a second expression, function of `t15`, and `t25`. Clearly the reasoning is that if `t23==0` then `t25!=0` and vice versa. However, when `t23==1`, `t25==0` and `t15==NaN` then `t27==NaN` because `0*NaN=NaN`. Thus,  the form is computed incorrectly. It should be

`double  t27  = (t13 ? (t24) : (((t14) * (((((-1) * (((t15) * (t24))))) + (((t26) * (t24))))))));`

I think this was introduced in this [commit](https://github.com/firedrakeproject/tsfc/commit/92cc254e3872ff72e901b2b5ed8768144b11f547), in an attempt to fix iusse #119  .

**Comment by wence-** [comment]
Agreed that the transformation: `Conditional(a, b, c) => Conditional(a, 1, 0)*b + Conditional(a, 0, 1)*c` is unsafe in the presence of NaNs.

**Comment by miklos1** [comment]
@mmorandi: What happens if you select `vanilla` mode? That should not rewrite conditionals like that...

**Comment by mmorandi** [comment]
@miklos1 : with `vanilla` mode everything seems to be fine.

**Comment by miklos1** [comment]
So this is another issues with the refactoriser, that is why it works in `vanilla` mode, which is a simple code generation pipeline without complicated optimisations, and which does not use the refactoriser, unlike the other modes (`tensor`, `coffee`, and `spectral`).

`spectral` and `coffee` modes require argument factorisation, which means separating the test functions, trial functions and the rest in each product.  This becomes problematic when both arguments appear inside a conditional, hence the substitution

    Conditional(a, b, c) => Conditional(a, 1, 0)*b + Conditional(a, 0, 1)*c

was introduced when “needed”.  This ‘need’ is actually defined a bit excessively, because it has been judged that factorising with smaller granularity yields more efficient code.  If I loosen this granularity with the following patch:

```diff
diff --git a/tsfc/spectral.py b/tsfc/spectral.py
index 585ded5..125f0a5 100644
--- a/tsfc/spectral.py
+++ b/tsfc/spectral.py
@@ -2,7 +2,7 @@ from collections import OrderedDict, defaultdict, namedtuple
 from functools import partial, reduce
 from itertools import chain, zip_longest
 
-from gem.gem import Delta, Indexed, Sum, index_sum, one
+from gem.gem import Conditional, Delta, Indexed, Sum, index_sum, one
 from gem.optimise import delta_elimination as _delta_elimination
 from gem.optimise import remove_componenttensors, replace_division, unroll_indexsum
 from gem.refactorise import ATOMIC, COMPOUND, OTHER, MonomialSum, collect_monomials
@@ -124,7 +124,7 @@ def classify(argument_indices, expression):
     if n == 0:
         return OTHER
     elif n == 1:
-        if isinstance(expression, (Delta, Indexed)):
+        if isinstance(expression, (Conditional, Delta, Indexed)):
             return ATOMIC
         else:
             return COMPOUND
```

then the first part of the quoted code snippet looks better:

```c
    double  t12  = ((((((t9) * (t9))) + (((t10) * (t10))))) + (((t11) * (t11))));
    double  t13  = ((t12) <= (1e-06));
    double  t14  = ((1) / (t12));
    double  t15  = ((sin(t12)) * (t14));
    double  t16  = (t13 ? t12 : t15);
```

however, it does not help the second part (i.e. `t23` to `t27`).

Since UFLACS must do argument factorisation (no “vanilla” mode), they had to deal with this problem earlier.  Back then I thought that one might work around the unsafety of the above conditional substitution by defining the UFL such that the test of the trial functions are outside the conditional.  However, I now see that this approach is not all practical when the actual UFL form itself is derived through automatic differentiation from a residual formulation.

The right approach seems to be a refactorisation of conditionals that distinguishes between safe and potentially unsafe calculations, a substitution like the following:

    Conditional(a, b_s*b_u, c_s*c_u) => Conditional(a, b_u, 0)*b_s + Conditional(a, 0, c_u)*c_s

where `s` subscript stands for ‘safe’, i.e. calculations that will surely yield a finite value, and `u` for ‘potentially unsafe’, i.e. calculations that might evaluate to infinity, minus infinity, or not-a-number.  Basically, basis functions evaluations are safe, anything else is potentially unsafe.  However, expressions inside conditionals may not be in such a nice product form, but generally more like a sum-of-products form, or something that is refactorisable to a sum-of-products form.  Which basically means that a sanely efficient implementation has to tightly integrate the refactorisation of conditionals into the refactoriser, rather than trying to deal with it as a preprocessing step (as it is done now).  Which makes this issue a relative of #166.

**Comment by miklos1** [comment]
A different, but related issue based on this example: UFL and the code generation stack would really need a proper `sinc` function.

**Comment by miklos1** [comment]
Fix in branch `fix/refactorise-conditional`. @mmorandi: can you please test if that branch fixes the issue for you? I will prepare a pull request...

**Comment by mmorandi** [comment]
@miklos1 : Fixed!
