### ISSUE TITLE
Formatting precision of floats seems to be buggy

### ISSUE THREAD

**Issue by blechta** [firedrakeproject/tsfc#64]
```
element = FiniteElement("Lagrange", triangle, 1)
v = TestFunction(element)
L = 1.23456789*v*dx
```
with `precision=6` gives `1.2346` while uflacs and quadrature do `1.23457`. On the other hand COFFEE formatting of arrays (different code path) produces right and consistent answer.

See the discussion at https://github.com/firedrakeproject/tsfc/pull/63#discussion_r83212244 for details.

**Comment by blechta** [comment]
Further formatting of zero is not reproducible. One can get `0.0` or `-0.0`, see http://fenics-bamboo.simula.no:8085/browse/FFC-FD30-38/artifact/RT/error.log/error.log.

**Comment by blechta** [comment]
Would this patch
```
diff --git a/coffee/base.py b/coffee/base.py
index b50b798..5a46112 100644
--- a/coffee/base.py
+++ b/coffee/base.py
@@ -269,6 +269,7 @@ class ArrayInit(Expr):
         elif isnan(v):
             return "NAN"
         elif abs(v - round(v, 1)) < eps:
+            if v == -0.0: v = 0.0
             return f_int % v
         else:
             return f % v
```
be acceptable to solve plus/minus zero issue?

**Comment by miklos1** [comment]
This `f_int` is confusing both in `coffee.base.ArrayInit._formatter` and in `ffc.cpp.set_floating_formatting`. While the name suggests that it is formatting integers, it rounds to a multiple of 0.1 and formats with 1 decimal digit (after the decimal point).

**Comment by miklos1** [comment]
Moreover a quick grep in FFC for `"epsilon"` suggests that the epsilon form compiler parameter is only being used by the tensor representation to skip small values, while for rounding tables and for all other uses `format["epsilon"]` is being used. `format["epsilon"]` does not come from `parameters["epsilon"]`, but it comes from [`parameters["precision"]`](https://bitbucket.org/fenics-project/ffc/src/2bfdac344b4edac50d478ad84d0a1c7ea2556a3f/ffc/cpp.py?at=master&fileviewer=file-view-default#cpp.py-729).

**Comment by miklos1** [comment]
The reason I was a bit surprised about the minus zeros, is that if a number rounds to `-0.0`, then it must be close to zero, and if it is formatted in COFFEE, then it probably comes from a tabulation matrix, but tabulation matrix entries have already been rounded to exactly `0.0`, so a minus sign could not have arisen.

It seems that we get the minus zeros because epsilon is smaller than precision, rather than being ten times as big, as it is in FFC.

**Comment by blechta** [comment]
You might be right. The suggested COFFEE patch did not seem to help when running tests locally.

**Comment by blechta** [comment]
There are 27 occurences of `-0.0` in `ffc-reference-data/r_tsfc/` now.

```
grep -r -- "-0\.0[^0-9]" ffc-reference-data/r_tsfc/
```

If you suggest a patch I can test it easily...

**Comment by miklos1** [comment]
> The suggested COFFEE patch did not seem to help when running tests locally.

I'm not surprised. `v` is the value before rounding, and that is unlikely to be equal to `-0.0`.

> If you suggest a patch I can test it easily...

I will...

**Comment by blechta** [comment]
> This f_int is confusing...

I think that the rationale here is to format numbers like `-0.50000000000003` to `-0.5` for which C++ compiler might generate more effective code, right?

**Comment by blechta** [comment]
> v is the value before rounding

Yes, I'm an idiot.

**Comment by miklos1** [comment]
@blechta: I pushed a patch as branch `fix-epsilon`.

**Comment by miklos1** [comment]
Continuing the discussion from the issue description (all the other comments above are talking about a separate but related issue), I suggest the following:

- Revert commit af4145ab65b68c4609377b8130597cb7d952fee1, i.e. format scalars up to precision digits, rather than precision minus one.
- On the other hand, round floating-point numbers if they are within `epsilon` (= 10 * 10^(-precision)) absolute difference to a **non-zero** integer. This kinda emulates what I think the minus one was supposed to achieve, yet doesn't destroy small (close to zero) numbers, as they could be user input ([FFC #127](https://bitbucket.org/fenics-project/ffc/issues/127)).

@wence-: As the committer of af4145ab65b68c4609377b8130597cb7d952fee1, what do you think?

**Comment by wence-** [comment]
I think that's fine.  I don't recall exactly what prompted me to make that change.

**Comment by miklos1** [comment]
My best guess (memory?) is that we were seeing numbers like `3.000000000001`.

**Comment by blechta** [comment]
@miklos1, I'm very busy until the new year. Would you like an access to [/blechta/tsfc/next](/blechta/tsfc/tree/next) and [blechta/COFFEE/next](/blechta/COFFEE/tree/next) to get the changes tested on [Bamboo](http://fenics-bamboo.simula.no:8085/browse/FFC)?

**Comment by miklos1** [comment]
@blechta: OK. Thanks, that would be good.

**Comment by blechta** [comment]
I'd granted you the access. Feel free to update the master if you're sure that the change is fine. You can only break FFC tsfc anf FFC tsfc next plans this way and nobody cares about them so far.

Have you been granted access to FFC reference already?

**Comment by miklos1** [comment]
@blechta: No, I only have read access to FFC reference data.
